const anionkation = {
    ionA: [
        "H⁻",
        "F⁻",
        "CI⁻",
        "Br⁻",
        "I⁻",
        "OH⁻",
        "CN⁻",
        "SCN⁻",
        "HCOO⁻",
        "CH3COO⁻",
        "O²⁻",
        "S²⁻",
        "N³⁻",
        "NO₂⁻",
        "NO₃⁻",
        "ClO⁻",
        "CIO₂⁻",
        "CIO₃⁻",
        "ClO₄⁻",
        "MnO₄⁻",
        "MnO₄²⁻",
        "SO₃²⁻",
        "SO₄²⁻",
        "S₂O₃²⁻",
        "CO₃²⁻",
        "C₂O₄²⁻",
        "CrO₄²⁻",
        "Cr₂O₇²⁻",
        "AsO₃³⁻",
        "AsO₄⁴⁻",
        "SbO₃³⁻",
        "SbO₄⁴⁻",
        "PO₃³⁻",
        "PO₄³⁻",
        "SiO₂³⁻",
        "BO₃³⁻",
        "P³⁻",
        "HCO3⁻",
        "SnO₂²⁻",
        "SnO₃²⁻",
        "[Fe(CN)₆]³⁻",
        "[Fe(CN)₆]⁴⁻",
        "CN₂²⁻",
        "OCN⁻"
    ],
    namaA: [
        "Hidrida",
        "Fluorida",
        "Klorida",
        "Bromida",
        "lodida",
        "Hidroksida",
        "Sianida",
        "Tiosianat",
        "Format/Formiat",
        "Asetat",
        "Oksida",
        "Sulfida",
        "Nitrida",
        "Nitrit",
        "Nitrat",
        "Hipoklorit/",
        "Klorit/ Br, I",
        "Klorat/ Br, I",
        "Perklorat/",
        "Permanganat",
        "Manganat",
        "Sulfit",
        "Sulfat",
        "Tiosulfat",
        "Karbonat",
        "Oksalat",
        "Kromat",
        "Bikromat",
        "Arsenit",
        "Arsenat",
        "Antimonit",
        "Antimonat",
        "Fosfit",
        "Fosfat",
        "Silikat",
        "Borat",
        "Fosfida",
        "Bikarbonat",
        "Stanit",
        "Stanat",
        "Ferisianida",
        "Ferosianida",
        "Siamida",
        "Sianat"
    ],
    ionK: [
            "H⁺",
            "NH₄⁺",
            "Li⁺",
            "Na⁺",
            "K+",
            "Rb⁺",
            "Ag⁺",
            "Be²⁺",
            "Mg²⁺",
            "Ca²⁺",
            "Sr²⁻",
            "Ba²⁺",
            "Zn²⁺",
            "Ni²⁺",
            "Cd²⁺",
            "Mn²⁺",
            "Mn⁴⁺",
            "Al³⁺",
            "Cr³⁺",
            "Bi³⁺",
            "Sn²⁺",
            "Sn²⁺",
            "Pb²⁻",
            "Pb⁴⁺",
            "Co²⁺",
            "Co³⁺",
            "Hg⁺",
            "Hg²⁺",
            "Fe²⁺",
            "Fe³⁺",
            "Cu⁺",
            "Cu²⁺",
            "Au⁺",
            "Au³⁺",
            "Pt⁴⁺",
            "Hg⁺",
            "Hg²⁺",
            "Fe²⁺",
            "Fe³⁺",
            "Cu⁺",
            "Cu²⁺",
            "Au⁺",
            "Au³⁺",
            "Pt⁴⁺",
        ],
      namaK: [
            "Hidrogen/Asam",
            "Amonium",
            "Litium",
            "Natrium",
            "Kalium",
            "Rubidium",
            "Perak",
            "Berelium",
            "Magnesium",
            "Kalsium",
            "Stronsium",
            "Barium",
            "Zink/Seng",
            "Nikel",
            "Kadmium",
            "Mangan(11)",
            "Mangan(IV)",
            "Aluminium",
            "Krom",
            "Bismut",
            "Timah (II)/ Stano",
            "Timan(IV)/ Stani",
            "Timbal(II) / Plumbo",
            "Timbal(IV) / Plumbi",
            "Kobal (II)",
            "Kobal(III)",
            "Raksa (I) / Merkuro",
            "Raksa (II) / Merkuri",
            "Besi (II) / Ferro",
            "Besi (III) / Ferri",
            "Tembaga(I) / Cupro",
            "Tembaga(II) / Cupri",
            "Emas (I) / Auro",
            "Emas (III) / Auri",
            "Platina (IV)",
            "Raksa (I) / Merkuro",
            "Raksa (II) / Merkuri",
            "Besi (II) / Ferro",
            "Besi (III) / Ferri",
            "Tembaga(I) / Cupro",
            "Tembaga(II) / Cupri",
            "Emas (I) / Auro",
            "Emas (III) / Auri",
            "Platina (IV)",
           
        ]
};
